name: selenium-ci

on:
  push:
  pull_request:

jobs:
  selenium-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ---- LINUX ----
      - name: Install Chrome for Testing (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          set -euxo pipefail
          VER="139.0.7258.128"
          BASE="https://storage.googleapis.com/chrome-for-testing-public/${VER}/linux64"
          mkdir -p tools
          curl -sSLo chrome-linux64.zip "$BASE/chrome-linux64.zip"
          curl -sSLo chromedriver-linux64.zip "$BASE/chromedriver-linux64.zip"
          unzip -q chrome-linux64.zip -d tools && rm chrome-linux64.zip
          unzip -q chromedriver-linux64.zip -d tools && rm chromedriver-linux64.zip
          CHROME_BIN="${GITHUB_WORKSPACE}/tools/chrome-linux64/chrome"
          DRIVER_DIR="${GITHUB_WORKSPACE}/tools/chromedriver-linux64"
          chmod +x "$CHROME_BIN" "$DRIVER_DIR/chromedriver"
          echo "CHROME_BINARY=$CHROME_BIN"   >> "$GITHUB_ENV"
          echo "CHROMEDRIVER_DIR=$DRIVER_DIR" >> "$GITHUB_ENV"

      # ---- WINDOWS ----
      - name: Install Chrome for Testing (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $VER  = '139.0.7258.128'
          $BASE = "https://storage.googleapis.com/chrome-for-testing-public/$VER/win64"
          New-Item -ItemType Directory -Force tools | Out-Null
          Invoke-WebRequest "$BASE/chrome-win64.zip" -OutFile chrome-win64.zip
          Invoke-WebRequest "$BASE/chromedriver-win64.zip" -OutFile chromedriver-win64.zip
          Expand-Archive chrome-win64.zip -DestinationPath tools -Force
          Expand-Archive chromedriver-win64.zip -DestinationPath tools -Force
          Remove-Item chrome-win64.zip, chromedriver-win64.zip -Force
          "CHROME_BINARY=$((Resolve-Path .	ools\chrome-win64\chrome.exe).Path)" | Out-File -FilePath $env:GITHUB_ENV -Append
          "CHROMEDRIVER_DIR=$((Resolve-Path .	ools\chromedriver-win64).Path)"   | Out-File -FilePath $env:GITHUB_ENV -Append
          $p="C:\Program Files\Google\Chrome\Application\chromedriver.exe"
          if (Test-Path $p) { Rename-Item $p "chromedriver-old.exe" -Force }

      # ---- BUILD & TEST ----
      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test (Linux headless via xvfb)
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "$GITHUB_WORKSPACE/TestResults"
          xvfb-run --auto-servernum             dotnet test SeleniumAutomation.Tests               -c Release --no-build -v n               --logger "trx;LogFileName=test_results.trx"               --results-directory "$GITHUB_WORKSPACE/TestResults"

      - name: Test (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force "$env:GITHUB_WORKSPACE\TestResults" | Out-Null
          dotnet test .\SeleniumAutomation.Tests `
            -c Release --no-build -v n `
            --logger "trx;LogFileName=test_results.trx" `
            --results-directory "$env:GITHUB_WORKSPACE\TestResults"

      # ---- ARTIFACTS ----
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          if-no-files-found: warn
          path: |
            TestResults/**/*.trx
            SeleniumAutomation.Tests/bin/**/TestResults/**/*.png
            SeleniumAutomation.Tests/bin/**/TestResults/**/*.html

      # ---- SUMMARY (filenevek + linkek) ----
      - name: Summarize results
        if: always()
        shell: bash
        run: |
          echo "## 🧪 Selenium Test Results" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          if compgen -G "TestResults/**/*.trx" > /dev/null; then
            echo "### Test Log (.trx)" >> "$GITHUB_STEP_SUMMARY"
            for f in TestResults/**/*.trx; do
              echo "- $(basename "$f")" >> "$GITHUB_STEP_SUMMARY"
            done
            echo "" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "_No TRX file found._" >> "$GITHUB_STEP_SUMMARY"
          fi
          if compgen -G "SeleniumAutomation.Tests/bin/**/TestResults/**/*.html" > /dev/null; then
            echo "### HTML snapshots" >> "$GITHUB_STEP_SUMMARY"
            for f in SeleniumAutomation.Tests/bin/**/TestResults/**/*.html; do
              echo "- $(basename "$f")" >> "$GITHUB_STEP_SUMMARY"
            done
            echo "" >> "$GITHUB_STEP_SUMMARY"
          fi

      # ---- INLINE SCREENSHOTS ----
      - name: Show screenshots in Job Summary (Linux)
        if: always() && startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          set -euo pipefail
          echo "## 📸 Screenshots" >> "$GITHUB_STEP_SUMMARY"
          count=0
          while IFS= read -r -d '' img; do
            name="$(basename "$img")"
            b64="$(base64 -w0 "$img" 2>/dev/null || base64 "$img")"
            echo "<details><summary>$name</summary><img src="data:image/png;base64,$b64" alt="$name" style="max-width: 100%; height: auto;" /></details>" >> "$GITHUB_STEP_SUMMARY"
            count=$((count+1))
            [ $count -ge 6 ] && break
          done < <(find SeleniumAutomation.Tests -type f -path "*/TestResults/*" -name "*.png" -print0 | sort -z)
          if [ $count -eq 0 ]; then
            echo "_No screenshots found._" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Show screenshots in Job Summary (Windows)
        if: always() && startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          $summary = $env:GITHUB_STEP_SUMMARY
          "# 📸 Screenshots" | Out-File -FilePath $summary -Append -Encoding utf8
          $pngs = Get-ChildItem -Path ".\SeleniumAutomation.Tests" -Recurse -Include *.png |
                  Where-Object { $_.FullName -match "TestResults" } |
                  Sort-Object FullName | Select-Object -First 6
          if ($pngs.Count -eq 0) {
            "_No screenshots found._" | Out-File -FilePath $summary -Append -Encoding utf8
          } else {
            foreach ($img in $pngs) {
              $bytes = [IO.File]::ReadAllBytes($img.FullName)
              $b64   = [Convert]::ToBase64String($bytes)
              $name  = $img.Name
              "<details><summary>$name</summary><img src=""data:image/png;base64,$b64"" alt=""$name"" style=""max-width: 100%; height: auto;"" /></details>" | Out-File -FilePath $summary -Append -Encoding utf8
            }
          }
