name: selenium-ci

on:
  push:
  pull_request:

jobs:
  selenium-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # ---- LINUX ----
      - name: Install Chrome for Testing (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          set -euxo pipefail
          VER="139.0.7258.128"
          BASE="https://storage.googleapis.com/chrome-for-testing-public/${VER}/linux64"
          mkdir -p tools
          curl -sSLo chrome-linux64.zip "$BASE/chrome-linux64.zip"
          curl -sSLo chromedriver-linux64.zip "$BASE/chromedriver-linux64.zip"
          unzip -q chrome-linux64.zip -d tools && rm chrome-linux64.zip
          unzip -q chromedriver-linux64.zip -d tools && rm chromedriver-linux64.zip

          # Local shell vars for chmod
          CHROME_BIN="${GITHUB_WORKSPACE}/tools/chrome-linux64/chrome"
          DRIVER_DIR="${GITHUB_WORKSPACE}/tools/chromedriver-linux64"

          chmod +x "$CHROME_BIN" "$DRIVER_DIR/chromedriver"

          # Export for next steps
          echo "CHROME_BINARY=$CHROME_BIN"   >> "$GITHUB_ENV"
          echo "CHROMEDRIVER_DIR=$DRIVER_DIR" >> "$GITHUB_ENV"

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test (Linux headless via xvfb)
        if: startsWith(matrix.os, 'ubuntu')
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "$GITHUB_WORKSPACE/TestResults"
          xvfb-run --auto-servernum             dotnet test SeleniumAutomation.Tests               --no-build --logger "trx;LogFileName=test_results.trx"               -- ResultsDirectory="$GITHUB_WORKSPACE/TestResults"

      # ---- WINDOWS ----
      - name: Install Chrome for Testing (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $VER  = '139.0.7258.128'
          $BASE = "https://storage.googleapis.com/chrome-for-testing-public/$VER/win64"

          New-Item -ItemType Directory -Force tools | Out-Null
          Invoke-WebRequest "$BASE/chrome-win64.zip" -OutFile chrome-win64.zip
          Invoke-WebRequest "$BASE/chromedriver-win64.zip" -OutFile chromedriver-win64.zip
          Expand-Archive chrome-win64.zip -DestinationPath tools -Force
          Expand-Archive chromedriver-win64.zip -DestinationPath tools -Force
          Remove-Item chrome-win64.zip, chromedriver-win64.zip -Force

          "CHROME_BINARY=$((Resolve-Path .\tools\chrome-win64\chrome.exe).Path)" | Out-File -FilePath $env:GITHUB_ENV -Append
          "CHROMEDRIVER_DIR=$((Resolve-Path .\tools\chromedriver-win64).Path)"   | Out-File -FilePath $env:GITHUB_ENV -Append

          # Optional: neutralize stale system driver
          $p="C:\Program Files\Google\Chrome\Application\chromedriver.exe"
          if (Test-Path $p) { Rename-Item $p "chromedriver-old.exe" -Force }

      - name: Test (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force "$env:GITHUB_WORKSPACE\TestResults" | Out-Null
          dotnet test .\SeleniumAutomation.Tests `
            --no-build --logger "trx;LogFileName=test_results.trx" `
            -- ResultsDirectory "$env:GITHUB_WORKSPACE\TestResults"

      # ---- ARTIFACTS ----
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          if-no-files-found: warn
          path: |
            TestResults/**/*.trx
            SeleniumAutomation.Tests/bin/**/TestResults/**/*.png
            SeleniumAutomation.Tests/bin/**/TestResults/**/*.html
